name: ChatFix
description: A plugin that changes how the chat works and allows operators to modify the prefix and suffix of individual players' messages.
version: '1.1.0'

main: net.dvmn2.chatFix.ChatFix
api-version: '1.21.11'
load: POSTWORLD

authors: [ DVMN2 ]

permissions:
  chatmanager.admin:
    description: Доступ к настройке локального/глобального чата игроков
    default: op
  chatmanager.seehidden:
    description: Доступ к просмотру тихих действий
    default: op
